doctrine:
    orm:
        mappings:
            TourzeMgmCoreBundle:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/packages/mgm-core-bundle/src/Entity'
                prefix: 'Tourze\MgmCoreBundle\Entity'
                alias: TourzeMgmCoreBundle